using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;



namespace TempleSignUp.Models
{
    //all the properties for the groups that sign up after they pick their slot time
    public class SignUpModel
    {
        //GroupID that is generated by Asp.Net
        [Required, Key]
        public int GroupID { get; set; }
        //Name of group which is a required field and will output error if not included
        [Required(ErrorMessage = "Please enter a group name")]
        public string GroupName { get; set; }
        //Size of group which is a required field and will output error if not included
        [Required(ErrorMessage = "Please enter the number of people in your group")]
        public int GroupSize { get; set; }
        //Email which is a required field and will output error if not included
        [Required(ErrorMessage = "Please enter your email address"), EmailAddress]
        public string Email { get; set; }
        //Phone Number for group which is not required field but will output error if not inputed in correct format
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Phone number must be 10 digits. Ex. 111-111-1111 or 111.111.1111 or 1111111111")]
        public string PhoneNumber { get; set; }
        [Required]
        //This will be inputed as the Tour Time Slot that the group selected
        public string TourTime { get; set; }

    }
}
